// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dghcmzyrivnpfwiaauqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnaGNtenlyaXZucGZ3aWFhdXFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMDI1NTIsImV4cCI6MjA2Mjg3ODU1Mn0.t2YNbKP7mV0fKPKBfMJBBMboiEAcpr0vs9m04NqYfV0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);